# Generated by Django 2.2.6 on 2019-10-07 20:27

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='xxxxxxxxx', max_length=10, unique=True, validators=[accounts.validators.phone_number_validation]),
        ),
    ]
