# Generated by Django 2.2.5 on 2019-09-26 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='birthday'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default='Gender', max_length=10, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pofileUsage',
            field=models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('BOTH', 'BOTH')], default='Profile Usage', max_length=15, verbose_name='profile usage'),
        ),
    ]
