# Generated by Django 2.2.6 on 2019-10-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191007_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='addess'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='last name'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pofileUsage',
            field=models.CharField(blank=True, choices=[('BUY', 'BUY'), ('SELL', 'SELL'), ('BOTH', 'BOTH')], max_length=15, null=True, verbose_name='profile usage'),
        ),
    ]
