# Generated by Django 2.2.5 on 2019-09-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190928_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='wilaya',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.CharField(blank=True, default='address', max_length=100, null=True, verbose_name='addess'),
        ),
    ]
