# Generated by Django 2.2.5 on 2019-09-26 19:04

import accounts.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('activitiy', models.CharField(choices=[('buy', 'BUY'), ('sell', 'SELL')], max_length=5, null=True)),
                ('price', models.FloatField(validators=[accounts.validators.positive_number_validation])),
                ('amount', models.FloatField(validators=[accounts.validators.positive_number_validation])),
                ('cost', models.FloatField(null=True, validators=[accounts.validators.positive_number_validation])),
                ('currency', models.CharField(choices=[('EUR', 'EUR'), ('USD', 'USD')], max_length=4)),
                ('message', models.CharField(blank=True, default='empty', max_length=255, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
