# Generated by Django 2.2.6 on 2019-10-08 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(choices=[('Bug', 'Bug'), ('Partenership', 'Partenership'), ('Donate', 'Donate'), ('Other', 'Other')], max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('contactMessage', models.CharField(max_length=400)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('notification', 'notification'), ('message', 'message')], max_length=20)),
                ('seen', models.BooleanField(default=False)),
                ('msg', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='notifications.Message')),
                ('notif', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.Offer')),
            ],
        ),
    ]
